### ISSUE TITLE
BufferBuilder????

### ISSUE THREAD

**Issue by MunityVR** [CJMinecraft01/CJCore#10]
The import in GuiCore doesn't exist in 1.10.2/1.11.2:

import net.minecraft.client.renderer.BufferBuilder;

**Comment by CJMinecraft01** [comment]
Would you mind showing me your build.gradle file so I can see how you have CJCore setup in your environment and also, what version of CJCore is this for?

**Comment by MunityVR** [comment]
Don't worry about, I just already fixed it xD
