### ISSUE TITLE
CJCORE crashing with custom mod which depends on cjcore to run

### ISSUE THREAD

**Issue by WIP03** [CJMinecraft01/CJCore#8]
Minecraft Crashes when my custom mod (Plastic Craft) is put into a game with CJCORE.

Crash Log: https://hastebin.com/qinaxufuba.cs

Class in my mod which uses CJCORE: https://hastebin.com/cuyurogecu.java

(also it crashes in the Initialization of the game and the mod works in the dev environment)

**Comment by CJMinecraft01** [comment]
This should be fixed in the latest update. If not, let me know by posting another issue.
