### ISSUE TITLE
Core crashing in dev enviroment

### ISSUE THREAD

**Issue by WIP03** [CJMinecraft01/CJCore#9]
Minecraft crashes in development environment preventing any further development of my mod 

crash log: https://hastebin.com/helopuwiva.rb

API's Using: CJCORE (latest), ic2 API (latest) and rf API (latest)

**Comment by CJMinecraft01** [comment]
Can you show the CJCore.cfg file?

**Comment by WIP03** [comment]
https://hastebin.com/vomafulizi.bash

**Comment by CJMinecraft01** [comment]
I've just done a commit but it won't fix your issue. I need to see the whole console log for when you hover over the item. You will need to re setup the project again

**Comment by WIP03** [comment]
console: https://hastebin.com/itutunamoy.sql

**Comment by CJMinecraft01** [comment]
So for some reason, the default energy unit is null. I'm going to investigate because that shouldn't happen

**Comment by CJMinecraft01** [comment]
Fixed in latest version
